# ==============================================================
# OpenClaw + Ollama — Windows Automated Setup Script
# Run this in PowerShell (right-click → Run as Administrator)
# ==============================================================
# What this script does:
#   1. Checks prerequisites (Docker Desktop, Git, Ollama)
#   2. Pulls your chosen Ollama model if not already downloaded
#   3. Clones the OpenClaw repo
#   4. Copies your config files into place
#   5. Builds the Docker image and starts the gateway
#   6. Prints your dashboard URL
# ==============================================================

param (
    # ── Edit these to match your setup ──────────────────────
    [string]$OllamaPrimaryModel  = "gpt-oss:20b",
    [string]$OllamaSubagentModel = "gemma3:12b",
    [string]$InstallDir          = "$env:USERPROFILE\openclaw",
    [string]$GatewayToken        = ""         # leave blank to auto-generate
)

# ── Colours ──────────────────────────────────────────────────
function Info  ($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Cyan    }
function OK    ($msg) { Write-Host "[ OK ]  $msg" -ForegroundColor Green   }
function Warn  ($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow  }
function Err   ($msg) { Write-Host "[ERR ]  $msg" -ForegroundColor Red     }
function Title ($msg) {
    Write-Host ""
    Write-Host "=====================================================" -ForegroundColor Magenta
    Write-Host "  $msg" -ForegroundColor Magenta
    Write-Host "=====================================================" -ForegroundColor Magenta
}

# ── Auto-generate a token if not provided ────────────────────
if (-not $GatewayToken) {
    Add-Type -AssemblyName System.Web
    $GatewayToken = [System.Web.Security.Membership]::GeneratePassword(32, 4)
    Info "Auto-generated gateway token."
}

# ─────────────────────────────────────────────────────────────
# STEP 1 — Prerequisite checks
# ─────────────────────────────────────────────────────────────
Title "Checking prerequisites"

# Docker Desktop
try {
    $dockerVersion = docker --version 2>&1
    OK "Docker found: $dockerVersion"
} catch {
    Err "Docker Desktop is not installed or not running."
    Err "Download from: https://www.docker.com/products/docker-desktop"
    exit 1
}

# Docker running?
try {
    docker info *>$null
    OK "Docker daemon is running."
} catch {
    Err "Docker daemon is not running. Please start Docker Desktop and try again."
    exit 1
}

# Git
try {
    $gitVersion = git --version 2>&1
    OK "Git found: $gitVersion"
} catch {
    Err "Git is not installed."
    Err "Download from: https://git-scm.com/download/win"
    exit 1
}

# Ollama
try {
    $ollamaVersion = ollama --version 2>&1
    OK "Ollama found: $ollamaVersion"
} catch {
    Warn "Ollama binary not found in PATH."
    Warn "Make sure Ollama is running on your machine (check system tray icon)."
    Warn "Download from: https://ollama.com"
    $continue = Read-Host "Continue anyway? (y/n)"
    if ($continue -ne "y") { exit 1 }
}

# ─────────────────────────────────────────────────────────────
# STEP 2 — Pull Ollama models
# ─────────────────────────────────────────────────────────────
Title "Pulling Ollama models (this may take a while on first run)"

Info "Pulling primary model: $OllamaPrimaryModel"
ollama pull $OllamaPrimaryModel
if ($LASTEXITCODE -ne 0) {
    Warn "Could not pull $OllamaPrimaryModel — check Ollama is running."
}

if ($OllamaSubagentModel -ne $OllamaPrimaryModel) {
    Info "Pulling subagent model: $OllamaSubagentModel"
    ollama pull $OllamaSubagentModel
}

OK "Models ready."

# ─────────────────────────────────────────────────────────────
# STEP 3 — Clone OpenClaw repo
# ─────────────────────────────────────────────────────────────
Title "Setting up OpenClaw directory"

if (Test-Path "$InstallDir\.git") {
    Info "OpenClaw repo already exists at $InstallDir — pulling latest..."
    Set-Location $InstallDir
    git pull
} else {
    Info "Cloning OpenClaw into $InstallDir ..."
    git clone https://github.com/openclaw/openclaw.git $InstallDir
    Set-Location $InstallDir
}
OK "Repo ready."

# ─────────────────────────────────────────────────────────────
# STEP 4 — Write .env file
# ─────────────────────────────────────────────────────────────
Title "Writing configuration files"

$envContent = @"
# Auto-generated by setup.ps1 — $(Get-Date -Format "yyyy-MM-dd HH:mm")
OPENCLAW_GATEWAY_TOKEN=$GatewayToken
OPENCLAW_PRIMARY_MODEL=ollama/$OllamaPrimaryModel
OPENCLAW_SUBAGENT_MODEL=ollama/$OllamaSubagentModel
OPENCLAW_OLLAMA_BASE_URL=http://host.docker.internal:11434/v1
OPENCLAW_GATEWAY_BIND=loopback
"@

Set-Content -Path "$InstallDir\.env" -Value $envContent
OK ".env written."

# ─────────────────────────────────────────────────────────────
# STEP 5 — Copy openclaw.json into the config directory
# ─────────────────────────────────────────────────────────────
$configDir = "$env:USERPROFILE\.openclaw"
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir | Out-Null
}

# Replace model names in the JSON template and write it out
$jsonTemplate = Get-Content "$PSScriptRoot\openclaw.json" -Raw
$jsonFinal = $jsonTemplate `
    -replace '"llama3.2:latest"', "`"$OllamaPrimaryModel`"" `
    -replace '"qwen2.5-coder:7b"', "`"$OllamaSubagentModel`""
Set-Content -Path "$configDir\openclaw.json" -Value $jsonFinal
OK "openclaw.json written to $configDir"

# ─────────────────────────────────────────────────────────────
# STEP 6 — Build Docker image and start gateway
# ─────────────────────────────────────────────────────────────
Title "Building Docker image (first build takes 3-10 minutes)"

docker compose build --progress=plain
if ($LASTEXITCODE -ne 0) {
    Err "Docker build failed. Check the output above."
    exit 1
}
OK "Image built."

Info "Starting gateway container..."
docker compose up -d openclaw-gateway
if ($LASTEXITCODE -ne 0) {
    Err "Failed to start gateway. Run: docker compose logs openclaw-gateway"
    exit 1
}

# Wait for health check to pass
Info "Waiting for gateway to become healthy (up to 60s)..."
$retries = 0
do {
    Start-Sleep -Seconds 5
    $retries++
    $health = docker inspect --format="{{.State.Health.Status}}" openclaw-gateway 2>$null
} while ($health -ne "healthy" -and $retries -lt 12)

if ($health -eq "healthy") {
    OK "Gateway is healthy!"
} else {
    Warn "Gateway health check timed out. It may still be starting."
    Warn "Check: docker compose logs openclaw-gateway"
}

# ─────────────────────────────────────────────────────────────
# DONE — Print dashboard URL
# ─────────────────────────────────────────────────────────────
Title "Setup complete!"

Write-Host ""
Write-Host "  Dashboard URL:" -ForegroundColor White
Write-Host "  http://localhost:18789/?token=$GatewayToken" -ForegroundColor Green
Write-Host ""
Write-Host "  SAVE THIS URL — you'll need the token to log in." -ForegroundColor Yellow
Write-Host ""
Write-Host "  Useful commands:" -ForegroundColor White
Write-Host "    Check status  : docker compose ps"
Write-Host "    View logs     : docker compose logs -f openclaw-gateway"
Write-Host "    Stop          : docker compose down"
Write-Host "    Restart       : docker compose restart openclaw-gateway"
Write-Host "    List models   : docker compose exec openclaw-gateway node dist/index.js models list"
Write-Host ""
